/**
 * Traces the ORIGINAL brand logo bitmap into an exact vector path —
 * zero hand-drawing, zero distortion. Pipeline: upscale 4× (smoother curve
 * fitting) → hard threshold (kills JPEG fuzz) → potrace.
 *
 * Run:  node scripts/trace-logo.mjs
 * Outputs the traced <path d> + viewBox to data/brand-logo-path.json and a
 * review render to logo-traced.png (pass an out path as argv[2]).
 */
import sharp from "sharp";
import potrace from "potrace";
import { writeFileSync } from "node:fs";

const SRC = "public/brand/logo-original.jpeg";

// 1. clean bitmap: upscale, flatten, hard threshold
const { data: png, info } = await sharp(SRC)
  .resize({ width: 1024 })
  .flatten({ background: "#ffffff" })
  .threshold(140)
  .png()
  .toBuffer({ resolveWithObject: true });

// 2. trace
const svg = await new Promise((resolve, reject) => {
  potrace.trace(
    png,
    { threshold: 128, turdSize: 60, optTolerance: 0.35, color: "black" },
    (err, out) => (err ? reject(err) : resolve(out)),
  );
});

// 3. extract the path + dimensions
const d = svg.match(/d="([^"]+)"/)?.[1];
const width = Number(svg.match(/width="(\d+)/)?.[1] ?? info.width);
const height = Number(svg.match(/height="(\d+)/)?.[1] ?? info.height);
if (!d) throw new Error("no path traced");

writeFileSync(
  "data/brand-logo-path.json",
  JSON.stringify({ traced_at: new Date().toISOString(), viewBox: `0 0 ${width} ${height}`, d }),
);
writeFileSync(
  "src/components/brand-path.ts",
  `// AUTO-GENERATED by scripts/trace-logo.mjs — exact vector trace of\n// public/brand/logo-original.jpeg. Do not edit by hand; re-run the script.\nexport const BRAND_LOGO = {\n  viewBox: "0 0 ${width} ${height}",\n  width: ${width},\n  height: ${height},\n  d: "${d}",\n};\n`,
);
console.log(`✓ traced: viewBox 0 0 ${width} ${height}, path ${d.length} chars → data/brand-logo-path.json + src/components/brand-path.ts`);

// 4. review render: traced vector next to nothing — inspect it visually
const review = `<svg xmlns="http://www.w3.org/2000/svg" width="${Math.round(width / 2)}" height="${Math.round(height / 2)}" viewBox="0 0 ${width} ${height}"><rect width="${width}" height="${height}" fill="#fff"/><path d="${d}" fill="#111"/></svg>`;
const out = process.argv[2] ?? "logo-traced.png";
writeFileSync(out, await sharp(Buffer.from(review)).png().toBuffer());
console.log(`✓ review render → ${out}`);
