/**
 * Traces the brand mark into a vector path as faithfully as a raster source
 * allows. Run:  node scripts/trace-logo.mjs
 *
 * WHY THIS WAS REDONE. The first version traced a 255x346 JPEG and UPSCALED
 * it to 1024 first. Upscaling a small lossy image invents blur, thresholding
 * that blur invents wobble, and the tracer then fitted curves to the wobble:
 * the result had 117 curve segments and ZERO straight lines, even though the
 * artwork is mostly straight-sided bands. It was smoothing compression noise.
 *
 * Now it traces the 1609x1474 master at native resolution, with settings that
 * respect the drawing:
 *   alphaMax 0.55  keep corners sharp. The default (1.0) rounds them, which is
 *                  wrong here: the tails are straight bands meeting at points.
 *                  Low enough for corners, high enough that the top loop stays
 *                  a true circle rather than a polygon.
 *   optTolerance   0.1 rather than 0.35, so curves hug the outline instead of
 *                  cutting corners off it.
 *   turdSize 2     the source is clean, so almost nothing should be discarded.
 *                  60 was tuned to delete JPEG speckle that no longer exists.
 *
 * A trace is still an approximation of a bitmap. The only route to a
 * mathematically identical mark is the designer's original vector file
 * (.ai/.eps/.pdf with real paths). The "2000x2000" SVG we were given is not
 * one: it is an SVG wrapper around this same bitmap.
 */
import sharp from "sharp";
import potrace from "potrace";
import { writeFileSync } from "node:fs";

const SRC = "public/brand/logo-source.png";

// 1. flatten transparency onto white and take a hard threshold. No resize:
//    the master already has more detail than the tracer needs.
const { data: png, info } = await sharp(SRC)
  .flatten({ background: "#ffffff" })
  .greyscale()
  .threshold(128)
  .png()
  .toBuffer({ resolveWithObject: true });

// 2. trace
const svg = await new Promise((resolve, reject) => {
  potrace.trace(
    png,
    {
      threshold: 128,
      turdSize: 2,
      alphaMax: 0.55,
      optTolerance: 0.1,
      turnPolicy: potrace.Potrace.TURNPOLICY_MINORITY,
      color: "black",
    },
    (err, out) => (err ? reject(err) : resolve(out)),
  );
});

// 3. extract the path + dimensions
const d = svg.match(/d="([^"]+)"/)?.[1];
const width = Number(svg.match(/width="(\d+)/)?.[1] ?? info.width);
const height = Number(svg.match(/height="(\d+)/)?.[1] ?? info.height);
if (!d) throw new Error("no path traced");

const curves = (d.match(/[CcSsQq]/g) ?? []).length;
const lines = (d.match(/[LlHhVv]/g) ?? []).length;

writeFileSync(
  "data/brand-logo-path.json",
  JSON.stringify({ traced_at: new Date().toISOString(), viewBox: `0 0 ${width} ${height}`, d }),
);
writeFileSync(
  "src/components/brand-path.ts",
  `// AUTO-GENERATED by scripts/trace-logo.mjs — vector trace of\n// public/brand/logo-source.png (1609x1474 master). Do not edit by hand;\n// re-run the script. If the original .ai/.eps/.pdf vector ever turns up,\n// use its path directly instead of tracing.\nexport const BRAND_LOGO = {\n  viewBox: "0 0 ${width} ${height}",\n  width: ${width},\n  height: ${height},\n  d: "${d}",\n};\n`,
);
console.log(`✓ traced ${width}x${height}: ${d.length} chars, ${curves} curves, ${lines} straight segments`);

// 4. fidelity check: rasterise the trace back at source size and diff it
//    against the original. A number beats an opinion about "looks right".
const rendered = await sharp(
  Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${info.width}" height="${info.height}" viewBox="0 0 ${width} ${height}"><rect width="${width}" height="${height}" fill="#fff"/><path d="${d}" fill="#000"/></svg>`,
  ),
)
  .greyscale()
  .threshold(128)
  .raw()
  .toBuffer();

const original = await sharp(SRC)
  .flatten({ background: "#ffffff" })
  .greyscale()
  .threshold(128)
  .raw()
  .toBuffer();

let differing = 0;
for (let i = 0; i < original.length; i++) if (original[i] !== rendered[i]) differing++;
const pct = (differing / original.length) * 100;
console.log(`✓ fidelity: ${differing.toLocaleString()} of ${original.length.toLocaleString()} pixels differ (${pct.toFixed(3)}%)`);

const out = process.argv[2] ?? "logo-traced.png";
writeFileSync(
  out,
  await sharp(
    Buffer.from(
      `<svg xmlns="http://www.w3.org/2000/svg" width="${Math.round(width / 2)}" height="${Math.round(height / 2)}" viewBox="0 0 ${width} ${height}"><rect width="${width}" height="${height}" fill="#fff"/><path d="${d}" fill="#111"/></svg>`,
    ),
  )
    .png()
    .toBuffer(),
);
console.log(`✓ review render → ${out}`);
